### ISSUE TITLE
HW3: Question about Buttons in Write Tab and Preview Tab

### ISSUE THREAD

**Issue by bumkyu00** [swsnu/swppfall2021#70]
The spec describes, there should be input + buttons in write tab and plain text + buttons in preview tab. Does it mean that the set of buttons should exist both in write tab and preview tab? Or could it be just one outside of the tabs?

**Comment by kdh0102** [comment]
The buttons (e.g. back-edit-article-button, confirm-edit-article-button) should exist in both the `write` and `preview` tabs.
I did not get what do you mean by `outside of the tabs`. Could you elaborate?

**Comment by bumkyu00** [comment]
I meant by 'outside of the tabs' that regardless of the tab selected, the same button is fixed.

**Comment by kdh0102** [comment]
I still do not understand the differences between the two: 1) buttons existing in both write and preview tab 2) buttons existing outside of the tabs.
I, instead, attached the example views of each write and preview tab. Please check and let me know if you have any more questions.

### Write tab:
<img width="668" alt="Screen Shot 2021-10-03 at 10 32 37 AM" src="https://user-images.githubusercontent.com/16721914/135736384-3b7c1a29-4e50-4aa4-be4d-a791b683cc1b.png">

### Preview tab:
<img width="507" alt="Screen Shot 2021-10-03 at 10 33 31 AM" src="https://user-images.githubusercontent.com/16721914/135736400-ad3c8128-8e71-487a-be83-08fc9e266be7.png">
